package com.hotworx.global;


public class WebServiceConstants {
    public static final String SERVICE_URL = "";
//    public static final String BASE_URL = "https://sailposapi.uhfdemo.com/api/v1/"; //"https://appadminnew.uhfdemo.com/mobileservice/";
    public static final String BASE_URL = "https://sailposapi.hotworx.net/api/v1/"; //"https://appadminnew.uhfdemo.com/mobileservice/";
    public static final String CUSTOM_BASE_URL = "https://sailposapi.hotworx.net/"; //"https://appadminnew.uhfdemo.com/mobileservice/";
    public static final String CUSTOM_SUB_URL = "https://sailposapi.hotworx.net/nutritionix/mobileservice_nut.php?action=";
    public static final String SUB_URL = "mobileservice.php?action="; //"mobileservice_intermittent.php?action=";
    public static final String SUB_URL_NUTRITION = "mobileservice.php?action="; //"mobileservice_intermittent.php?action=";
    public static final String SUB_URL_INTERMITTENT = "mobileservice.php?action="; //"mobileservice_intermittent.php?action=";


     //"https://appadminnew.uhfdemo.com/mobileservice/";
    public static final String Login = "Login";
    public static final String OVERALL_SUMMARY = "OVERALL_SUMMARY";
    public static final String GET_WEIGHT = "GET_WEIGHT";
    public static final String SET_WEIGHT = "SET_WEIGHT";
    public static final String CALORIES_STAT = "CALORIES_STAT";
    public static final String VIEW_PROFILE = "VIEW_PROFILE";
    public static final String SAVE_PROFILE = "SAVE_PROFILE";
    public static final String Help = "Help";
    public static final String Feedback = "Feedback";
    public static final String PrivacyPolicy = "PrivacyPolicy";
    public static final String Booking_Appointments = "Booking_Appointments";
    public static final String GetNinetyDaySummary = "GetNinetyDaySummary";
    public static final String GET_REDEMPTION_STATUS = "GET_REDEMPTION_STATUS";
    public static final String MARK_REDEMPTION = "MARK_REDEMPTION";
    public static final String GET_LOCAL_LEADERBOARD = "GET_LOCAL_LEADERBOARD";
    public static final String GET_GLOBAL_LEADERBOARD = "GET_GLOBAL_LEADERBOARD";
    public static final String GET_USER_ACTIVITY = "GET_USER_ACTIVITY";
    public static final String GET_THIRTY_DAY_SUMMARY = "GET_THIRTY_DAY_SUMMARY";
    public static final String GET_NUTRITION_CALORIES = "GET_NUTRITION_CALORIES";
    public static final String GET_INTERMITTENT_PLAN = "GET_INTERMITTENT_PLAN";
    public static final String SET_INTERMITTENT_PLAN = "SET_INTERMITTENT_PLAN";
    public static final String GET_INTERMITTENT_FOOD = "GET_INTERMITTENT_FOOD";
    public static final String DELETE_NUTRITION = "DELETE_NUTRITION";
    public static final String SET_HEIGHT_WEIGHT = "SET_HEIGHT_WEIGHT";
    public static final String ADD_EXERCISE = "ADD_EXERCISE";
    public static final String DELETE_EXERCISE = "DELETE_EXERCISE";
    public static final String VIEW_NUTRITION_SUMMARY = "VIEW_NUTRITION_SUMMARY";
    public static final String GET_FOOD = "GET_FOOD";
    public static final String GET_FAVORITE_FOOD = "GET_FAVORITE_FOOD";
    public static final String SET_FAVORITE_FOOD = "SET_FAVORITE_FOOD";
    public static final String GET_BARCODE_FOOD = "GET_BARCODE_FOOD";
    public static final String GET_EXERCISE_DATA = "GET_EXERCISE_DATA";
    public static final String GET_BODY_FAT_GRAPH = "GET_BODY_FAT_GRAPH";
    public static final String GET_TODAYS_SESSION = "GET_TODAYS_SESSION";
    public static final String GET_FINAL_SUMMARY = "GET_FINAL_SUMMARY";
    public static final String SHARE_FACEBOOK = "SHARE_FACEBOOK";
    public static final String GET_REWARD = "GET_REWARD";
    public static final String START_SESSION_BURNT_CALORIES ="START_SESSION_BURNT_CALORIES" ;
    public static final String SAVE_SESSION_BURNT_CALORIES = "SAVE_SESSION_BURNT_CALORIES";
    public static final String SAVE_AFTER_BURNT_CALORIES = "SAVE_AFTER_BURNT_CALORIES" ;
    public static final String Cancel_Session = "Cancel_Session";
    public static final String UPLOAD_IMAGE = "UPLOAD_IMAGE" ;
    public static final String RECORD_MONTHLY_BODY_FAT = "RECORD_MONTHLY_BODY_FAT" ;
    public static final String GET_VPT_VIDEO = "GET_VPT_VIDEO";
    public static final String ADD_VIDEO_HISTORY = "ADD_VIDEO_HISTORY";
    public static final String ADD_CALORIE = "ADD_CALORIE";
    public static final String ADD_INTERMITTENT_CALORIE = "ADD_INTERMITTENT_CALORIE";
    public static final String FRANCHISE_LIST = "FRANCHISE_LIST";
    public static final String FRANCHISE_SUMMARY = "FRANCHISE_SUMMARY";
    public static final String GET_FULL_SUMMARY = "GET_FULL_SUMMARY" ;
    public static final String UPDATE_FIREBASE_TOKEN = "UPDATE_FIREBASE_TOKEN" ;
    public static final String ADD_USER_NOTIFICATION_ACTION = "ADD_USER_NOTIFICATION_ACTION" ;
    public static final String GET_NOTIFICATION_HISTORY = "GET_NOTIFICATION_HISTORY" ;
    public static final String GET_SQUAD_LIST = "GET_SQUAD_LIST" ;
    public static final String MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ" ;
    public static final String MARK_ATTACHMENT_READ = "MARK_ATTACHMENT_READ" ;
}
