package com.passio.modulepassio.models.HotsquadList.Passio

data class ReferenceNutrients(
    val refCalcium: RefCalcium,
    val refCalories: RefCalories,
    val refCarbs: RefCarbs,
    val refCholesterol: RefCholesterol,
    val refFat: RefFat,
    val refFibers: RefFibers,
    val refFolicAcid: RefFolicAcid,
    val refIron: RefIron,
    val refMagnesium: RefMagnesium,
    val refMonounsaturatedFat: RefMonounsaturatedFat,
    val refPhosphorus: RefPhosphorus,
    val refPolyunsaturatedFat: RefPolyunsaturatedFat,
    val refPotassium: RefPotassium,
    val refProteins: RefProteins,
    val refSatFat: RefSatFat,
    val refSelenium: RefSelenium,
    val refSodium: RefSodium,
    val refSugars: RefSugars,
    val refTransFat: RefTransFat,
    val refVitaminA: Int,
    val refVitaminB12: RefVitaminB12,
    val refVitaminB12Added: RefVitaminB12Added,
    val refVitaminB6: RefVitaminB12,
    val refVitaminC: RefVitaminC,
    val refVitaminD: RefVitaminD,
    val refVitaminE: RefVitaminE,
    val refVitaminEAdded: RefVitaminEAdded,
    val refVitaminKPhylloquinone: RefVitaminKPhylloquinone,
    val refZinc: RefZinc,
    val referenceWeight: ReferenceWeightX,
    val weight: WeightX
)